# Фінальний проєкт: схема `pandemic`, нормалізація та аналітика `infectious_cases`

**Датасет.** `infectious_cases.csv` — 10 521 рядок статистики інфекційних захворювань
(Our World in Data / IHME): 245 унікальних значень `Entity` (країни **та** агрегати —
`World`, регіони WHO, групи Світового банку), роки **1920–2023** і 9 показників
захворюваності.

**Що в цьому notebook:**

| Завдання | Зміст |
|---|---|
| Setup | PostgreSQL 16 всередині notebook через `pgserver`, пошук CSV локально / у Colab |
| Завдання 1 | `CREATE SCHEMA pandemic`, staging-таблиця `infectious_cases`, імпорт через `COPY`, профіль даних |
| Завдання 2 | нормалізація до 3НФ: `entities` (унікальні `Entity` + `Code`) і `disease_cases` (показники по `entity_id`) |
| Завдання 3 | `AVG` / `MIN` / `MAX` / `SUM` по `Number_rabies`, топ-10 за середнім |
| Завдання 4 | `MAKE_DATE`, `CURRENT_DATE`, `AGE` — колонка різниці в роках |
| Завдання 5 | власні функції `years_since_year()` і `avg_cases_per_period()` + їх використання |
| Перевірка | `assert`-и по всіх завданнях у кінці notebook |

**Відтворюваність.** Notebook проходить `Restart & Run All`: усі `DROP ... IF EXISTS` перед
DDL, `TRUNCATE` перед `COPY`, жодного `RANDOM()`. Єдине, що змінюється між запусками, —
колонки, похідні від `CURRENT_DATE` (завдання 4 і 5), і це свідомо: саме цього вимагає умова.

---

## Setup

### Чому PostgreSQL піднімається в самому notebook

`pgserver` ставить і запускає справжній PostgreSQL 16 у тимчасовому каталозі процесу, тому
notebook працює і в Colab, і локально без зовнішнього сервера, портів і паролів. SQL
виконується магіями **JupySQL** (`%%sql`), результат одразу стає `pandas.DataFrame`. Python
залишений лише там, де SQL не дотягується: старт сервера, пошук CSV, `COPY ... FROM STDIN`
і фінальні `assert`-и.

In [1]:
%pip install -q pgserver psycopg2-binary "sqlalchemy>=2.0" pandas jupysql tzdata

Note: you may need to restart the kernel to use updated packages.

In [2]:
# ============================================================
# Imports, шляхи, старт PostgreSQL
# ============================================================

import shutil
import sys
import tempfile
import time
from pathlib import Path
from urllib.error import URLError
from urllib.request import urlopen

import pandas as pd
import pgserver
from sqlalchemy import create_engine, text

IN_COLAB = "google.colab" in sys.modules
BASE_DIR = Path("/content") if IN_COLAB else Path.cwd()

pd.set_option("display.max_rows", 30)
pd.set_option("display.max_columns", 40)
pd.set_option("display.width", 220)
pd.set_option("display.max_colwidth", 60)


def ensure_pg_timezone_files():
    """Windows-білд pgserver не містить share/postgresql/timezone.

    Без цих файлів сервер стартує з TimeZone=GMT, і будь-яке іменоване часове
    пояс кидає помилку. У Colab (Linux) каталог уже на місці, тому функція
    нічого не робить.
    """
    tz_dir = Path(pgserver.__file__).parent / "pginstall" / "share" / "postgresql" / "timezone"
    if tz_dir.exists():
        return False
    import tzdata

    shutil.copytree(Path(tzdata.__file__).parent / "zoneinfo", tz_dir)
    return True


patched_tz = ensure_pg_timezone_files()
CLUSTER_DIR = Path(tempfile.gettempdir()) / "goit_rdb_fp_pg"
pg = pgserver.get_server(str(CLUSTER_DIR), cleanup_mode="stop")

# SQLAlchemy 2.1 мапить "postgresql://" на psycopg (v3); явно просимо psycopg2,
# бо саме його cursor.copy_expert() використовується для COPY ... FROM STDIN.
# search_path у connect_args діє на КОЖНЕ з'єднання — і на JupySQL, і на
# raw_connection() для COPY, тому "SET search_path" із завдання 1 не губиться
# при перепідключенні.
engine = create_engine(
    pg.get_uri().replace("postgresql://", "postgresql+psycopg2://"),
    connect_args={"options": "-csearch_path=pandemic,public"},
)

print("Colab:            ", IN_COLAB)
print("timezone patched: ", patched_tz)
print("cluster:          ", CLUSTER_DIR)
print("engine:           ", engine.url.render_as_string(hide_password=True))

Colab:             False
timezone patched:  False
cluster:           C:\Users\Asus\AppData\Local\Temp\goit_rdb_fp_pg
engine:            postgresql+psycopg2://postgres:***@127.0.0.1:49793/postgres

In [3]:
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.displaycon = False
%config SqlMagic.feedback = 1
%sql engine

%sql SELECT version() AS server_version, CURRENT_DATE AS today;

1 rows affected.

                                                server_version       today
0  PostgreSQL 16.2 on x86_64-pc-mingw64, compiled by gcc.ex...  2026-10-18

### Пошук `infectious_cases.csv` — локально і в Colab

Файл лежить у репозиторії поряд із notebook, тому локально він знаходиться одразу. У Colab
локального файлу немає, і клітинка нижче пробує стратегії **по порядку**, друкуючи, яка
саме спрацювала:

1. **локальні шляхи** — каталог notebook, `/content`, `/content/data`, змонтований
   Google Drive (`/content/drive/MyDrive`);
2. **`CSV_URL`** — raw-посилання на файл у публічному репозиторії `goit-rdb-fp`
   (працює після `git push`, 3 спроби з паузами);
3. **`files.upload()`** — інтерактивне завантаження з комп'ютера, якщо репозиторій ще не
   опублікований або немає мережі;
4. інакше — явний `FileNotFoundError` з інструкцією, що зробити.

Так один і той самий notebook виконується без правок у Colab, у PyCharm і в локальному
Jupyter.

In [4]:
# ============================================================
# Пошук / завантаження CSV
# ============================================================

CSV_NAME = "infectious_cases.csv"
CSV_URL = "https://raw.githubusercontent.com/IYgit/goit-rdb-fp/main/infectious_cases.csv"
EXPECTED_COLUMNS = [
    "Entity", "Code", "Year", "Number_yaws", "polio_cases", "cases_guinea_worm",
    "Number_rabies", "Number_malaria", "Number_hiv", "Number_tuberculosis",
    "Number_smallpox", "Number_cholera_cases",
]


def local_candidates():
    """Шляхи, де CSV може лежати локально або в уже змонтованому Drive."""
    directories = [
        BASE_DIR,
        Path.cwd(),
        Path("/content"),
        Path("/content/data"),
        Path("/content/drive/MyDrive"),
        Path("/content/drive/MyDrive/goit-rdb-fp"),
        BASE_DIR / "data",
    ]
    seen, candidates = set(), []
    for directory in directories:
        path = directory / CSV_NAME
        key = str(path).lower()
        if key not in seen:
            seen.add(key)
            candidates.append(path)
    return candidates


def download_csv(destination, attempts=3):
    """Тягне CSV з CSV_URL; True, якщо вдалося."""
    for attempt in range(1, attempts + 1):
        try:
            with urlopen(CSV_URL, timeout=60) as response:
                payload = response.read()
            destination.write_bytes(payload)
            print(f"[2] завантажено з CSV_URL: {len(payload) / 1024:.0f} КБ -> {destination}")
            return True
        except (URLError, OSError, TimeoutError) as error:
            print(f"[2] спроба {attempt}/{attempts} не вдалася — {type(error).__name__}: {error}")
            time.sleep(2 * attempt)
    return False


def upload_csv(destination):
    """Інтерактивний fallback лише для Colab."""
    from google.colab import files

    print("[3] завантажте infectious_cases.csv з комп'ютера:")
    uploaded = files.upload()
    for name, payload in uploaded.items():
        if name.lower().endswith(".csv"):
            destination.write_bytes(payload)
            print(f"[3] збережено {name} -> {destination}")
            return True
    return False


def resolve_csv():
    for path in local_candidates():
        if path.exists() and path.stat().st_size > 10_000:
            print(f"[1] знайдено локально: {path}")
            return path

    destination = BASE_DIR / CSV_NAME
    if download_csv(destination):
        return destination

    if IN_COLAB and upload_csv(destination):
        return destination

    raise FileNotFoundError(
        f"{CSV_NAME} не знайдено. Покладіть файл поряд із notebook "
        f"(або в /content у Colab) чи виправте CSV_URL."
    )


CSV_PATH = resolve_csv()

lines = CSV_PATH.read_text(encoding="utf-8-sig").splitlines()
assert lines[0].split(",") == EXPECTED_COLUMNS, lines[0]
print(f"\nрядків з даними: {len(lines) - 1:,}".replace(",", " "))
print("колонки:        ", ", ".join(EXPECTED_COLUMNS))

[1] знайдено локально: C:\Work\GoIT\Relational Databases\goit-rdb-fp\infectious_cases.csv

рядків з даними: 10 521
колонки:         Entity, Code, Year, Number_yaws, polio_cases, cases_guinea_worm, Number_rabies, Number_malaria, Number_hiv, Number_tuberculosis, Number_smallpox, Number_cholera_cases

---

## Завдання 1. Схема `pandemic` і завантаження даних

Команди створення схеми — дослівно з умови. `SET search_path` діє в межах сесії, тому той
самий `search_path` продубльовано в `connect_args` engine (див. setup): інакше `COPY` через
окреме з'єднання не побачив би схему, і далі довелося б усюди писати повне ім'я.

In [5]:
%%sql
CREATE SCHEMA IF NOT EXISTS pandemic;
SET search_path TO pandemic;

Empty DataFrame
Columns: []
Index: []

### Staging-таблиця: усі колонки `TEXT`

Дані імпортуються **як є**, текстом, і лише потім типізуються (завдання 2). Причини:

* `COPY` не падає на жодному значенні — якщо в CSV колись з'явиться `"n/a"` чи `" 12 "`,
  рядок усе одно завантажиться, а проблему буде видно запитом, а не трейсбеком;
* лишається «сире» джерело, з яким можна порівняти нормалізовані таблиці (нижче є такий
  тест на втрату даних);
* завдання 5 прямо просить працювати «лише з числовими значеннями» — ця перевірка має сенс
  тільки на нетипізованих даних.

Імена колонок — у нижньому регістрі (конвенція PostgreSQL). Це не ламає умову: PostgreSQL
складає нелапковані ідентифікатори в нижній регістр, тому `Number_rabies` у запиті й
`number_rabies` у таблиці — той самий атрибут.

In [6]:
%%sql
DROP TABLE IF EXISTS pandemic.disease_cases;
DROP TABLE IF EXISTS pandemic.entities;
DROP TABLE IF EXISTS pandemic.infectious_cases;

CREATE TABLE pandemic.infectious_cases (
    entity                TEXT,
    code                  TEXT,
    year                  TEXT,
    number_yaws           TEXT,
    polio_cases           TEXT,
    cases_guinea_worm     TEXT,
    number_rabies         TEXT,
    number_malaria        TEXT,
    number_hiv            TEXT,
    number_tuberculosis   TEXT,
    number_smallpox       TEXT,
    number_cholera_cases  TEXT
);

Empty DataFrame
Columns: []
Index: []

Імпорт — серверним `COPY ... FROM STDIN WITH (FORMAT CSV, HEADER true)` через
`psycopg2.cursor.copy_expert()`. Це той самий механізм, що й `\copy` у `psql`, тільки
керований з Python: один прохід по файлу, без побудови `INSERT`-ів. У форматі CSV **порожнє
нелапковане поле `COPY` вважає `NULL`**, тому пропуски в даних одразу стають `NULL`, а не
порожніми рядками. `TRUNCATE` робить клітинку ідемпотентною.

In [7]:
COPY_SQL = """
COPY pandemic.infectious_cases (
    entity, code, year, number_yaws, polio_cases, cases_guinea_worm,
    number_rabies, number_malaria, number_hiv, number_tuberculosis,
    number_smallpox, number_cholera_cases
)
FROM STDIN WITH (FORMAT CSV, HEADER true)
"""

connection = engine.raw_connection()
try:
    with connection.cursor() as cursor:
        cursor.execute("TRUNCATE pandemic.infectious_cases")
        with open(CSV_PATH, "r", encoding="utf-8-sig", newline="") as handle:
            cursor.copy_expert(COPY_SQL, handle)
        copied = cursor.rowcount
    connection.commit()
finally:
    connection.close()

print(f"COPY завантажив {copied:,} рядків".replace(",", " "))

COPY завантажив 10 521 рядків

In [8]:
%%sql
SELECT * FROM pandemic.infectious_cases LIMIT 10;

10 rows affected.

        entity code  year number_yaws polio_cases cases_guinea_worm number_rabies number_malaria number_hiv number_tuberculosis number_smallpox number_cholera_cases
0  Afghanistan  AFG  1980        None        6160                 0          None           None       None                None            None                 None
1  Afghanistan  AFG  1981        None        5859                 0          None           None       None                None            None                 None
2  Afghanistan  AFG  1982        None        9730                 0          None           None       None                None            None                 None
3  Afghanistan  AFG  1983        None       13937                 0          None           None       None                None            None                 None
4  Afghanistan  AFG  1984        None        3864                 0          None           None       None                None            None                 None
5  Afghanistan  AFG  1985        None       13867                 0          None           None       None                None            None                 None
6  Afghanistan  AFG  1986        None       12901                 0          None           None       None                None            None                 None
7  Afghanistan  AFG  1987        None        4396                 0          None           None       None                None            None                 None
8  Afghanistan  AFG  1988        None        2149                 0          None           None       None                None            None                 None
9  Afghanistan  AFG  1989        None         385                 0          None           None       None                None            None                 None

**Висновок 1.1.** Структура одного рядка — `(Entity, Code, Year)` + 9 показників. Уже на
перших рядках видно головну рису датасету: він **розріджений**. Для Афганістану 1980-х
заповнені лише `polio_cases` і `cases_guinea_worm`, решта — `NULL`. Отже, агрегати далі
треба читати як «по тих роках, де спостереження є», а не «за весь період».

In [9]:
%%sql
SELECT
    measure.name                                                         AS column_name,
    COUNT(*) FILTER (WHERE measure.value IS NOT NULL)                    AS filled,
    ROUND(100.0 * COUNT(*) FILTER (WHERE measure.value IS NOT NULL) / COUNT(*), 1) AS filled_pct,
    COUNT(*) FILTER (WHERE measure.value IS NOT NULL
                       AND NOT pg_input_is_valid(measure.value, 'numeric')) AS non_numeric,
    COUNT(*) FILTER (WHERE measure.value LIKE '%.%')                     AS fractional
FROM pandemic.infectious_cases AS ic
CROSS JOIN LATERAL (
    VALUES ('number_yaws',          ic.number_yaws),
           ('polio_cases',          ic.polio_cases),
           ('cases_guinea_worm',    ic.cases_guinea_worm),
           ('number_rabies',        ic.number_rabies),
           ('number_malaria',       ic.number_malaria),
           ('number_hiv',           ic.number_hiv),
           ('number_tuberculosis',  ic.number_tuberculosis),
           ('number_smallpox',      ic.number_smallpox),
           ('number_cholera_cases', ic.number_cholera_cases)
) AS measure(name, value)
GROUP BY measure.name
ORDER BY filled DESC;

9 rows affected.

            column_name  filled filled_pct  non_numeric  fractional
0     cases_guinea_worm    8428       80.1            0           0
1           polio_cases    7610       72.3            0           0
2        number_malaria    6780       64.4            0        2672
3         number_rabies    6780       64.4            0        6780
4            number_hiv    6780       64.4            0        6729
5   number_tuberculosis    6780       64.4            0        6649
6  number_cholera_cases    2967       28.2            0           0
7       number_smallpox     104        1.0            0           0
8           number_yaws      74        0.7            0           0

**Висновок 1.2.** `pg_input_is_valid(..., 'numeric')` (PostgreSQL 16) перевіряє значення
без ризику впасти на помилці приведення типів: **нечислових значень немає жодного** —
«нечисловим» у цьому CSV є тільки порожнє поле. Два практичні наслідки:

* заповненість колонок дуже різна: `cases_guinea_worm` і `polio_cases` — 80.1 % і 72.3 %,
  а `number_smallpox` і `number_yaws` — 1.0 % і 0.7 % (104 і 74 рядки на 10 521);
* `number_rabies`, `number_hiv`, `number_tuberculosis`, `number_malaria` **дробові** — це
  модельні оцінки IHME, а не підрахунок випадків. Тому в нормалізованій таблиці типом буде
  `NUMERIC`: `INTEGER` відкинув би дробову частину, а `DOUBLE PRECISION` додав би похибку
  двійкового представлення.

In [10]:
%%sql
SELECT
    COUNT(*)                                           AS n_rows,
    COUNT(DISTINCT entity)                             AS n_entities,
    COUNT(DISTINCT code)                               AS n_codes,
    COUNT(*) FILTER (WHERE code IS NULL)               AS rows_without_code,
    COUNT(DISTINCT entity) FILTER (WHERE code IS NULL) AS entities_without_code,
    MIN(year::INT)                                     AS first_year,
    MAX(year::INT)                                     AS last_year,
    COUNT(DISTINCT (entity, year))                     AS unique_entity_year
FROM pandemic.infectious_cases;

1 rows affected.

   n_rows  n_entities  n_codes  rows_without_code  entities_without_code  first_year  last_year  unique_entity_year
0   10521         245      211               1128                     34        1920       2023               10521

**Висновок 1.3.** 10 521 рядок, 245 унікальних `Entity`, роки 1920–2023. Два факти, які
визначають усе подальше:

* `COUNT(DISTINCT (entity, year))` = `COUNT(*)` = 10 521 → пара **`(Entity, Year)` є
  природним ключем**, дублів немає;
* `Code` порожній у 1 128 рядках, тобто у 34 значень `Entity`. Це не «діри в даних», а
  агрегати: `World`, `Africa`, `European Region (WHO)`, `OECD Countries`,
  `Lower Middle Income (WB)`. ISO-коду в них немає за визначенням, тому в нормалізованій
  таблиці `code` буде `NULL`-able. Трьом агрегатам OWID усе ж присвоїв власні коди
  (`OWID_WRL`, `OWID_SRM`, `OWID_YGS`) — через них довжина колонки `VARCHAR(8)`, а не
  `CHAR(3)`.

---

## Завдання 2. Нормалізація до 3-ї нормальної форми

**Що саме порушено.** Ключ таблиці — `(Entity, Year)` (перевірено вище). Залежності:

* `(Entity, Year) → Number_rabies, Number_malaria, …` — показники залежать від **повного**
  ключа;
* `Entity → Code` — код залежить **лише від частини ключа**.

Друга залежність і є проблемою: це часткова залежність неключового атрибута, тобто
порушення 2НФ (а отже й 3НФ, яка її включає). Практична ціна — `Code` повторюється стільки
разів, скільки років є в сутності (у середньому 43 рядки на одну), і нічого не заважає
записати `UKR` в одному рядку й `UKA` в іншому.

**Декомпозиція:**

| Таблиця | Ключ | Вміст |
|---|---|---|
| `pandemic.entities` | `entity_id` (сурогатний), `entity` UNIQUE | унікальні пари `Entity` + `Code` |
| `pandemic.disease_cases` | `(entity_id, year)` | 9 показників, замість `Entity`/`Code` — `entity_id` |

**Чому це вже 3НФ, а не лише 2НФ.** Транзитивних залежностей не залишилось: у `entities`
від ключа залежить тільки `code`, у `disease_cases` кожен показник залежить від повного
ключа `(entity_id, year)` і не визначає жодного іншого показника.

**Чому 9 показників лишаються в одному рядку.** Це не порушення 3НФ: усі вони залежать від
повного ключа й нічого не визначають між собою. Нормальні форми не вимагають «довгого»
формату `(entity_id, year, disease, value)` — це вже рішення про зручність, а умова просить
саме «таблицю з основними показниками захворювань».

Нижче — перевірка, що `Entity → Code` справді функціональна залежність: запит має
повернути **0 рядків**, інакше `DISTINCT` при заповненні `entities` розмножив би сутності.

In [11]:
%%sql
SELECT entity, COUNT(DISTINCT code) AS distinct_codes
FROM pandemic.infectious_cases
GROUP BY entity
HAVING COUNT(DISTINCT code) > 1;

Empty DataFrame
Columns: [entity, distinct_codes]
Index: []

**Висновок 2.1.** Порожній результат: кожному `Entity` відповідає рівно один `Code` (або
жодного). Декомпозиція буде без втрат, можна створювати таблиці.

In [12]:
%%sql
CREATE TABLE pandemic.entities (
    entity_id  SERIAL       PRIMARY KEY,
    entity     TEXT         NOT NULL UNIQUE,
    code       VARCHAR(8)
);

CREATE TABLE pandemic.disease_cases (
    entity_id             INTEGER  NOT NULL REFERENCES pandemic.entities (entity_id),
    year                  SMALLINT NOT NULL,
    number_yaws           NUMERIC,
    polio_cases           NUMERIC,
    cases_guinea_worm     NUMERIC,
    number_rabies         NUMERIC,
    number_malaria        NUMERIC,
    number_hiv            NUMERIC,
    number_tuberculosis   NUMERIC,
    number_smallpox       NUMERIC,
    number_cholera_cases  NUMERIC,
    PRIMARY KEY (entity_id, year)
);

CREATE INDEX ix_disease_cases_year ON pandemic.disease_cases (year);

Empty DataFrame
Columns: []
Index: []

`entities` заповнюється унікальними парами; `TRIM` + `NULLIF` прибирають можливі пробіли й порожній код.

In [13]:
%%sql
INSERT INTO pandemic.entities (entity, code)
SELECT DISTINCT TRIM(entity), NULLIF(TRIM(code), '')
FROM pandemic.infectious_cases
ORDER BY 1;

245 rows affected.

Empty DataFrame
Columns: []
Index: []

In [14]:
%%sql
INSERT INTO pandemic.disease_cases (
    entity_id, year, number_yaws, polio_cases, cases_guinea_worm, number_rabies,
    number_malaria, number_hiv, number_tuberculosis, number_smallpox, number_cholera_cases
)
SELECT
    e.entity_id,
    ic.year::SMALLINT,
    ic.number_yaws::NUMERIC,
    ic.polio_cases::NUMERIC,
    ic.cases_guinea_worm::NUMERIC,
    ic.number_rabies::NUMERIC,
    ic.number_malaria::NUMERIC,
    ic.number_hiv::NUMERIC,
    ic.number_tuberculosis::NUMERIC,
    ic.number_smallpox::NUMERIC,
    ic.number_cholera_cases::NUMERIC
FROM pandemic.infectious_cases AS ic
JOIN pandemic.entities AS e ON e.entity = TRIM(ic.entity);

10521 rows affected.

Empty DataFrame
Columns: []
Index: []

In [15]:
%%sql
SELECT
    (SELECT COUNT(*) FROM pandemic.infectious_cases)            AS staging_rows,
    (SELECT COUNT(*) FROM pandemic.entities)                    AS entities_rows,
    (SELECT COUNT(*) FROM pandemic.disease_cases)               AS disease_cases_rows,
    (SELECT COUNT(*) FROM pandemic.entities WHERE code IS NULL) AS entities_without_code,
    (SELECT COUNT(*) FROM pandemic.disease_cases d
       LEFT JOIN pandemic.entities e USING (entity_id)
      WHERE e.entity_id IS NULL)                                AS orphan_rows;

1 rows affected.

   staging_rows  entities_rows  disease_cases_rows  entities_without_code  orphan_rows
0         10521            245               10521                     34            0

**Висновок 2.2.** 10 521 → 10 521: жодного рядка не втрачено й не продубльовано,
`entities` — 245 рядків (з них 34 без коду), «сиріт» немає, бо `entity_id` захищений
`FOREIGN KEY`.

Окремо перевіряємо, що **типізація нічого не змінила**: порівнюємо кожен показник
нормалізованої таблиці з приведеним до `NUMERIC` значенням зі staging. `IS DISTINCT FROM`
тут принциповий — звичайне `<>` на `NULL` дало б `NULL` і тихо пропустило б розбіжність.

In [16]:
%%sql
SELECT COUNT(*) AS mismatched_rows
FROM pandemic.infectious_cases AS ic
JOIN pandemic.entities AS e      ON e.entity = TRIM(ic.entity)
JOIN pandemic.disease_cases AS d ON d.entity_id = e.entity_id
                                AND d.year = ic.year::SMALLINT
WHERE d.number_yaws          IS DISTINCT FROM ic.number_yaws::NUMERIC
   OR d.polio_cases          IS DISTINCT FROM ic.polio_cases::NUMERIC
   OR d.cases_guinea_worm    IS DISTINCT FROM ic.cases_guinea_worm::NUMERIC
   OR d.number_rabies        IS DISTINCT FROM ic.number_rabies::NUMERIC
   OR d.number_malaria       IS DISTINCT FROM ic.number_malaria::NUMERIC
   OR d.number_hiv           IS DISTINCT FROM ic.number_hiv::NUMERIC
   OR d.number_tuberculosis  IS DISTINCT FROM ic.number_tuberculosis::NUMERIC
   OR d.number_smallpox      IS DISTINCT FROM ic.number_smallpox::NUMERIC
   OR d.number_cholera_cases IS DISTINCT FROM ic.number_cholera_cases::NUMERIC;

1 rows affected.

   mismatched_rows
0                0

In [17]:
%%sql
SELECT e.entity, e.code, d.year,
       d.number_rabies, d.number_tuberculosis, d.number_hiv
FROM pandemic.disease_cases AS d
JOIN pandemic.entities AS e USING (entity_id)
WHERE e.code = 'UKR' AND d.year BETWEEN 2014 AND 2019
ORDER BY d.year;

6 rows affected.

    entity code  year number_rabies number_tuberculosis number_hiv
0  Ukraine  UKR  2014      6.690502           44876.883  20523.984
1  Ukraine  UKR  2015     6.9275784             45017.2  26778.217
2  Ukraine  UKR  2016     6.4714775           44917.637  34291.773
3  Ukraine  UKR  2017     5.8461995           44583.926  34344.234
4  Ukraine  UKR  2018      5.504843           42812.465  34281.453
5  Ukraine  UKR  2019     5.2199264           39574.203  33620.082

**Висновок 2.3.** `mismatched_rows = 0` — приведення `TEXT → NUMERIC` пройшло без втрат.
Контрольна вибірка по Україні читається так само, як початковий CSV, але `Entity`/`Code`
приходять уже з довідника через `JOIN` по `entity_id`.

---

## Завдання 3. Статистика по `Number_rabies`

`AVG`, `MIN`, `MAX`, `SUM` для кожної унікальної пари `Entity`/`Code` — групуємо по
`entity_id` (ключ довідника), назву й код підтягуємо `JOIN`-ом. `COUNT(number_rabies)`
додано як кількість років, по яких узагалі є спостереження.

In [18]:
%%sql
SELECT
    e.entity_id,
    e.entity,
    e.code,
    COUNT(d.number_rabies)          AS years_observed,
    ROUND(AVG(d.number_rabies), 4)  AS avg_rabies,
    ROUND(MIN(d.number_rabies), 4)  AS min_rabies,
    ROUND(MAX(d.number_rabies), 4)  AS max_rabies,
    ROUND(SUM(d.number_rabies), 4)  AS sum_rabies
FROM pandemic.disease_cases AS d
JOIN pandemic.entities AS e USING (entity_id)
GROUP BY e.entity_id, e.entity, e.code
HAVING COUNT(d.number_rabies) > 0
ORDER BY avg_rabies DESC
LIMIT 10;

10 rows affected.

   entity_id                        entity      code  years_observed  avg_rabies  min_rabies  max_rabies   sum_rabies
0        241                         World  OWID_WRL              30  20192.3704  14075.5080  24744.6580  605771.1110
1        121      Lower Middle Income (WB)       NaN              30  15193.9594  10202.5280  19182.7950  455818.7815
2        204               South Asia (WB)       NaN              30  11729.8888   7271.2754  15361.8780  351896.6626
3        201  South-East Asia Region (WHO)       NaN              30  11424.3269   6806.0127  15641.9580  342729.8068
4         77                           G20       NaN              30  10189.0460   6339.0796  13164.8810  305671.3801
5         97                         India       IND              30   8599.1733   5425.8726  11121.1420  257975.1984
6        209       Sub-Saharan Africa (WB)       NaN              30   4748.2681   4356.8184   5017.9770  142448.0427
7          3          African Region (WHO)       NaN              30   4649.7024   4283.0730   4917.7840  139491.0713
8        120               Low Income (WB)       NaN              30   3568.1055   3014.6170   3873.5330  107043.1635
9         58      East Asia & Pacific (WB)       NaN              30   3427.4611   2009.9395   4591.0107  102823.8340

**Висновок 3.1.** Топ-10 за середнім — це майже суцільно **агрегати**, а не країни:
`World` (≈20 192 смертей на рік), `Lower Middle Income (WB)`, `South Asia (WB)`,
`South-East Asia Region (WHO)`, `G20`. Єдина справжня країна в десятці — **Індія**
(≈8 599 на рік, тобто ~43 % світового показника). Це властивість датасету: країни й
агрегати лежать в одній таблиці, і будь-який рейтинг «за величиною» витягує агрегати
нагору. `years_observed = 30` у всіх десяти рядках: оцінки IHME по сказу охоплюють
1990–2019 роки.

Два технічні моменти, важливі для коректності цього запиту:

* **`HAVING COUNT(d.number_rabies) > 0` обов'язковий.** У PostgreSQL `ORDER BY ... DESC`
  за замовчуванням ставить `NULL` **першими** (`DESC NULLS FIRST`). У 19 із 245 сутностей
  немає жодного спостереження по сказу → `AVG` повертає `NULL` → без `HAVING` вони
  зайняли б усю першу десятку. Альтернатива — `ORDER BY avg_rabies DESC NULLS LAST`.
* **`AVG` ділить на кількість не-`NULL` значень**, а не на кількість рядків групи, тому
  `avg_rabies × years_observed = sum_rabies`, і середнє не «розмивається» роками без даних.

Нижче — демонстрація тієї самої пастки: той самий запит без `HAVING`.

In [19]:
%%sql
SELECT
    e.entity,
    COUNT(d.number_rabies)         AS years_observed,
    ROUND(AVG(d.number_rabies), 4) AS avg_rabies
FROM pandemic.disease_cases AS d
JOIN pandemic.entities AS e USING (entity_id)
GROUP BY e.entity_id, e.entity
ORDER BY avg_rabies DESC
LIMIT 5;

5 rows affected.

                           entity  years_observed avg_rabies
0                          Africa               0       None
1                         Reunion               0       None
2                            Asia               0       None
3                         Oceania               0       None
4  Serbia and Montenegro (former)               0       None

**Висновок 3.2.** Без фільтра перші рядки — сутності з `years_observed = 0` і
`avg_rabies = NULL`: континентальні агрегати (`Africa`, `Asia`, `Oceania`), яких немає в
оцінках IHME по сказу, малі території (`Reunion`) та історичні утворення
(`Serbia and Montenegro (former)`). Порядок між самими `NULL`-ами при цьому довільний —
база не має чим їх розрізнити. Саме такий «топ» отримують, якщо не врахувати `NULLS FIRST`.

Для повноти — той самий рейтинг лише по країнах: відкидаємо агрегати умовою
`code IS NOT NULL AND code NOT LIKE 'OWID%'` (ISO-код є тільки в країн, а три псевдокоди
OWID належать агрегатам).

In [20]:
%%sql
SELECT
    e.entity,
    e.code,
    COUNT(d.number_rabies)          AS years_observed,
    ROUND(AVG(d.number_rabies), 4)  AS avg_rabies,
    ROUND(MIN(d.number_rabies), 4)  AS min_rabies,
    ROUND(MAX(d.number_rabies), 4)  AS max_rabies,
    ROUND(SUM(d.number_rabies), 4)  AS sum_rabies
FROM pandemic.disease_cases AS d
JOIN pandemic.entities AS e USING (entity_id)
WHERE e.code IS NOT NULL AND e.code NOT LIKE 'OWID%'
GROUP BY e.entity_id, e.entity, e.code
HAVING COUNT(d.number_rabies) > 0
ORDER BY avg_rabies DESC
LIMIT 10;

10 rows affected.

        entity code  years_observed avg_rabies min_rabies  max_rabies   sum_rabies
0        India  IND              30  8599.1733  5425.8726  11121.1420  257975.1984
1     Pakistan  PAK              30  1582.1696  1177.1449   1881.7257   47465.0888
2      Nigeria  NGA              30  1335.4155  1073.9458   1441.1188   40062.4646
3        China  CHN              30  1247.9067   744.2510   2075.5930   37437.2020
4     Ethiopia  ETH              30  1145.1725   758.0497   1323.4026   34355.1757
5      Myanmar  MMR              30   972.9037   560.6968   1449.8279   29187.1106
6   Bangladesh  BGD              30   785.7088   180.4026   1734.7075   23571.2647
7        Nepal  NPL              30   661.2509   338.1352   1041.6312   19837.5259
8  Philippines  PHL              30   618.6910   358.0602    898.0710   18560.7302
9    Indonesia  IDN              30   267.7148   124.6217    481.3748    8031.4428

**Висновок 3.3.** Серед країн картина очікувана: Індія (8 599 на рік), далі Пакистан,
Нігерія, Китай, Ефіопія, М'янма, Бангладеш, Непал, Філіппіни, Індонезія — країни з великим
населенням і високим тягарем сказу. Розкид між `min_rabies` і `max_rabies` показує
динаміку за 1990–2019: Індія 11 121 → 5 591, Китай 1 373 → 753, Бангладеш 1 309 → 180,
тобто в усіх трьох показник суттєво знизився (у Бангладеш — більш ніж у сім разів).

---

## Завдання 4. Різниця в роках вбудованими функціями

Три атрибути з умови:

* `MAKE_DATE(year, 1, 1)` — 1 січня відповідного року. `MAKE_DATE` надійніший за
  конкатенацію `TO_DATE(year || '-01-01', 'YYYY-MM-DD')`: приймає числа й не залежить від
  формату рядка;
* `CURRENT_DATE` — поточна дата;
* `EXTRACT(YEAR FROM AGE(CURRENT_DATE, MAKE_DATE(year, 1, 1)))` — різниця в роках.

Четверта колонка, `years_diff_calendar`, додана для порівняння двох **різних** семантик:
`AGE` дає кількість **повних** років (інтервал), а `DATE_PART('year', CURRENT_DATE) - year`
— різницю календарних років. Для 1 січня вони завжди збігаються (річниця 1 січня вже
настала), але для довільної дати — ні, і наступна клітинка це показує.

In [21]:
%%sql
SELECT
    e.entity,
    d.year,
    MAKE_DATE(d.year::INT, 1, 1)                                             AS year_start,
    CURRENT_DATE                                                             AS today,
    EXTRACT(YEAR FROM AGE(CURRENT_DATE, MAKE_DATE(d.year::INT, 1, 1)))::INT  AS years_diff,
    (DATE_PART('year', CURRENT_DATE) - d.year)::INT                          AS years_diff_calendar,
    AGE(CURRENT_DATE, MAKE_DATE(d.year::INT, 1, 1))::TEXT                    AS full_age_interval
FROM pandemic.disease_cases AS d
JOIN pandemic.entities AS e USING (entity_id)
WHERE e.code = 'UKR'
ORDER BY d.year DESC
LIMIT 10;

10 rows affected.

    entity  year  year_start       today  years_diff  years_diff_calendar        full_age_interval
0  Ukraine  2022  2022-01-01  2026-10-18           4                    4   4 years 9 mons 17 days
1  Ukraine  2021  2021-01-01  2026-10-18           5                    5   5 years 9 mons 17 days
2  Ukraine  2020  2020-01-01  2026-10-18           6                    6   6 years 9 mons 17 days
3  Ukraine  2019  2019-01-01  2026-10-18           7                    7   7 years 9 mons 17 days
4  Ukraine  2018  2018-01-01  2026-10-18           8                    8   8 years 9 mons 17 days
5  Ukraine  2017  2017-01-01  2026-10-18           9                    9   9 years 9 mons 17 days
6  Ukraine  2016  2016-01-01  2026-10-18          10                   10  10 years 9 mons 17 days
7  Ukraine  2015  2015-01-01  2026-10-18          11                   11  11 years 9 mons 17 days
8  Ukraine  2014  2014-01-01  2026-10-18          12                   12  12 years 9 mons 17 days
9  Ukraine  2013  2013-01-01  2026-10-18          13                   13  13 years 9 mons 17 days

In [22]:
%%sql
SELECT
    sample.label,
    sample.event_date,
    CURRENT_DATE                                                 AS today,
    EXTRACT(YEAR FROM AGE(CURRENT_DATE, sample.event_date))::INT AS years_diff_age,
    (DATE_PART('year', CURRENT_DATE) - DATE_PART('year', sample.event_date))::INT
                                                                 AS years_diff_calendar
FROM (VALUES ('1 січня 1996',   DATE '1996-01-01'),
             ('1 липня 1996',   DATE '1996-07-01'),
             ('31 грудня 1996', DATE '1996-12-31')) AS sample(label, event_date);

3 rows affected.

            label  event_date       today  years_diff_age  years_diff_calendar
0    1 січня 1996  1996-01-01  2026-10-18              30                   30
1    1 липня 1996  1996-07-01  2026-10-18              30                   30
2  31 грудня 1996  1996-12-31  2026-10-18              29                   30

**Висновок 4.** Для 1 січня `years_diff` і `years_diff_calendar` ідентичні, і це очікувано:
річниця 1 січня настає на початку року, тому повних років стільки ж, скільки різниця
календарних. Контрольна клітинка показує, де семантики розходяться: для `1996-12-31`
річниця цього року ще не настала, тож `AGE` дає **29**, а віднімання календарних років —
**30**. Для `1996-07-01` при запуску в жовтні річниця вже минула, тому обидва значення
збігаються — тобто розбіжність залежить не лише від дати в даних, а й від дня запуску.
Оскільки умова просить саме «1 січня», обидва варіанти коректні, але у власній функції
(завдання 5) використано `AGE`: вона залишається правильною для будь-якої дати.

`full_age_interval` показує, звідки беруться роки: `AGE` повертає повний `INTERVAL`
(`4 years 9 mons 17 days`), з якого `EXTRACT(YEAR ...)` бере лише роки. Приведення
`::TEXT` тут не косметика — psycopg2 мапить `INTERVAL` на `datetime.timedelta`, і pandas
показав би інтервал у днях, втративши структуру «роки / місяці / дні».

---

## Завдання 5. Власні функції

### 5.1 `years_since_year(year)` — різниця в роках

`LANGUAGE sql` (одновиразова функція — планувальник може її інлайнити) і **`STABLE`**, а не
`IMMUTABLE`: результат залежить від `CURRENT_DATE`, тож незмінним у часі він не є, але в
межах одного запиту стабільний. `RETURNS NULL ON NULL INPUT` робить `NULL` на вході
`NULL`-ом на виході без зайвої перевірки в тілі.

In [23]:
%%sql
CREATE OR REPLACE FUNCTION pandemic.years_since_year(p_year INTEGER)
RETURNS INTEGER
LANGUAGE sql
STABLE
RETURNS NULL ON NULL INPUT
AS $$
    SELECT EXTRACT(YEAR FROM AGE(CURRENT_DATE, MAKE_DATE(p_year, 1, 1)))::INTEGER;
$$;

COMMENT ON FUNCTION pandemic.years_since_year(INTEGER) IS
    'Різниця в повних роках між CURRENT_DATE і 1 січня вказаного року';

Empty DataFrame
Columns: []
Index: []

### 5.2 `avg_cases_per_period(cases, divisor)` — середня кількість за період

`LANGUAGE plpgsql`, бо потрібна явна перевірка дільника, і **`IMMUTABLE`**: на однакових
аргументах результат завжди однаковий, тому PostgreSQL може кешувати виклики й
використовувати функцію в індексах за виразом. Дільник `0` або `NULL` дає `NULL`, а не
`division_by_zero`: в аналітичному запиті по 10 тисячах рядків краще отримати порожню
клітинку, ніж перерваний запит.

In [24]:
%%sql
CREATE OR REPLACE FUNCTION pandemic.avg_cases_per_period(
    p_cases   NUMERIC,
    p_divisor NUMERIC
)
RETURNS NUMERIC
LANGUAGE plpgsql
IMMUTABLE
AS $$
BEGIN
    IF p_cases IS NULL OR p_divisor IS NULL OR p_divisor = 0 THEN
        RETURN NULL;
    END IF;

    RETURN ROUND(p_cases / p_divisor, 2);
END;
$$;

COMMENT ON FUNCTION pandemic.avg_cases_per_period(NUMERIC, NUMERIC) IS
    'Середня кількість захворювань за період: річна кількість / дільник (12, 4, 2 ...)';

Empty DataFrame
Columns: []
Index: []

Перевірка на прикладі з умови (`1996 → 1996-01-01 → різниця`) і на всіх трьох дільниках.

In [25]:
%%sql
SELECT
    1996                                    AS year_in,
    MAKE_DATE(1996, 1, 1)                   AS year_start,
    CURRENT_DATE                            AS today,
    pandemic.years_since_year(1996)         AS years_since_year,
    pandemic.years_since_year(NULL)         AS null_input,
    pandemic.avg_cases_per_period(1200, 12) AS per_month,
    pandemic.avg_cases_per_period(1200, 4)  AS per_quarter,
    pandemic.avg_cases_per_period(1200, 2)  AS per_half_year,
    pandemic.avg_cases_per_period(1200, 0)  AS divisor_zero,
    pandemic.avg_cases_per_period(NULL, 12) AS cases_null;

1 rows affected.

   year_in  year_start       today  years_since_year null_input per_month per_quarter per_half_year divisor_zero cases_null
0     1996  1996-01-01  2026-10-18                30       None    100.00      300.00        600.00         None       None

**Висновок 5.1.** `1996 → 1996-01-01 → 30` повних років (станом на дату запуску), що
збігається з колонкою `years_diff` із завдання 4. Для 1200 випадків на рік функція дає
100.00 на місяць, 300.00 на квартал і 600.00 на півріччя — співвідношення 1 : 3 : 6
витримане. `NULL` і нульовий дільник повертають `NULL` замість помилки.

### 5.3 Використання функцій у запитах

Обидві функції в одному `SELECT` по нормалізованій таблиці. Умова «лише числові значення»
тут виконується через `IS NOT NULL`: після типізації в колонці `NUMERIC` за визначенням не
може бути нечислового значення.

In [26]:
%%sql
SELECT
    e.entity,
    e.code,
    d.year,
    pandemic.years_since_year(d.year::INT)              AS years_since_year,
    d.number_rabies                                     AS cases_per_year,
    pandemic.avg_cases_per_period(d.number_rabies, 12)  AS avg_per_month,
    pandemic.avg_cases_per_period(d.number_rabies, 4)   AS avg_per_quarter,
    pandemic.avg_cases_per_period(d.number_rabies, 2)   AS avg_per_half_year
FROM pandemic.disease_cases AS d
JOIN pandemic.entities AS e USING (entity_id)
WHERE d.number_rabies IS NOT NULL
ORDER BY d.number_rabies DESC
LIMIT 10;

10 rows affected.

  entity      code  year  years_since_year cases_per_year avg_per_month avg_per_quarter avg_per_half_year
0  World  OWID_WRL  1990                36      24744.658       2062.05         6186.16          12372.33
1  World  OWID_WRL  1991                35      24559.182       2046.60         6139.80          12279.59
2  World  OWID_WRL  1992                34      24337.137       2028.09         6084.28          12168.57
3  World  OWID_WRL  1993                33      24127.453       2010.62         6031.86          12063.73
4  World  OWID_WRL  1994                32       23972.55       1997.71         5993.14          11986.28
5  World  OWID_WRL  1995                31      23905.242       1992.10         5976.31          11952.62
6  World  OWID_WRL  1996                30      23831.625       1985.97         5957.91          11915.81
7  World  OWID_WRL  1997                29      23652.562       1971.05         5913.14          11826.28
8  World  OWID_WRL  1998                28       23415.79       1951.32         5853.95          11707.90
9  World  OWID_WRL  1999                27      23185.303       1932.11         5796.33          11592.65

Той самий запит на **staging-таблиці**, де `number_rabies` — `TEXT`. Ось тут вимога
«використовуйте лише записи, у яких значення кількості захворювань є числовим» стає
справжнім фільтром: без нього `number_rabies::NUMERIC` впав би на першому ж нечисловому
значенні. Фільтр заданий регулярним виразом; наступна клітинка порівнює його з
`pg_input_is_valid()`.

In [27]:
%%sql
SELECT
    ic.entity,
    ic.year::INT                                                 AS year,
    pandemic.years_since_year(ic.year::INT)                      AS years_since_year,
    ic.number_rabies::NUMERIC                                    AS cases_per_year,
    pandemic.avg_cases_per_period(ic.number_rabies::NUMERIC, 12) AS avg_per_month,
    pandemic.avg_cases_per_period(ic.number_rabies::NUMERIC, 4)  AS avg_per_quarter,
    pandemic.avg_cases_per_period(ic.number_rabies::NUMERIC, 2)  AS avg_per_half_year
FROM pandemic.infectious_cases AS ic
WHERE ic.number_rabies ~ '^-?[0-9]+(\.[0-9]+)?([eE][-+]?[0-9]+)?$'
ORDER BY ic.number_rabies::NUMERIC DESC
LIMIT 10;

10 rows affected.

  entity  year  years_since_year cases_per_year avg_per_month avg_per_quarter avg_per_half_year
0  World  1990                36      24744.658       2062.05         6186.16          12372.33
1  World  1991                35      24559.182       2046.60         6139.80          12279.59
2  World  1992                34      24337.137       2028.09         6084.28          12168.57
3  World  1993                33      24127.453       2010.62         6031.86          12063.73
4  World  1994                32       23972.55       1997.71         5993.14          11986.28
5  World  1995                31      23905.242       1992.10         5976.31          11952.62
6  World  1996                30      23831.625       1985.97         5957.91          11915.81
7  World  1997                29      23652.562       1971.05         5913.14          11826.28
8  World  1998                28       23415.79       1951.32         5853.95          11707.90
9  World  1999                27      23185.303       1932.11         5796.33          11592.65

In [28]:
%%sql
SELECT
    (SELECT COUNT(*) FROM pandemic.infectious_cases
      WHERE number_rabies ~ '^-?[0-9]+(\.[0-9]+)?([eE][-+]?[0-9]+)?$')           AS numeric_by_regex,
    (SELECT COUNT(*) FROM pandemic.infectious_cases
      WHERE number_rabies IS NOT NULL
        AND pg_input_is_valid(number_rabies, 'numeric'))                         AS numeric_by_parser,
    (SELECT COUNT(*) FROM pandemic.disease_cases WHERE number_rabies IS NOT NULL) AS numeric_in_typed_table,
    (SELECT COUNT(*) FROM pandemic.infectious_cases WHERE number_rabies IS NULL)  AS empty_values;

1 rows affected.

   numeric_by_regex  numeric_by_parser  numeric_in_typed_table  empty_values
0              6780               6780                    6780          3741

**Висновок 5.2.** Усі три способи відбору числових значень дають **6 780** рядків, решта
3 741 — порожні значення. Тобто фільтр не викидає жодного «майже числового» значення: у
цьому CSV єдиний нечисловий варіант — відсутнє значення.

Чим відрізняються способи:

* **регулярний вираз** працює будь-де, але його легко написати неточно — наведений шаблон
  свідомо допускає знак, дробову частину й експоненту (`5.5e-05` у даних по сказу
  трапляється);
* **`pg_input_is_valid(value, 'numeric')`** (PostgreSQL 16) перевіряє значення
  *справжнім парсером типу*, тому точніший за будь-який regexp — це кращий вибір, якщо
  версія сервера дозволяє;
* **`IS NOT NULL` на типізованій колонці** — найдешевший: один раз перевірили під час
  нормалізації й далі покладаємось на тип.

Найбільші значення в обох варіантах запиту однакові (`World`, 1990 рік, ≈24 745 смертей),
а `avg_per_month` / `avg_per_quarter` / `avg_per_half_year` відрізняються рівно в 3 і 6
разів — функція працює як задумано.

---

## Фінальна перевірка

Клітинка нижче перевіряє `assert`-ами всі контрольні точки проєкту. Якщо notebook
виконується `Restart & Run All` без помилок — усі завдання дали очікуваний результат.

In [29]:
# ============================================================
# Автоматична перевірка всіх завдань
# ============================================================


def scalar(sql_text):
    with engine.connect() as connection:
        return connection.execute(text(sql_text)).scalar()


def frame(sql_text):
    with engine.connect() as connection:
        return pd.read_sql(text(sql_text), connection)


# --- завдання 1: схема й імпорт
assert scalar("""SELECT COUNT(*) FROM information_schema.schemata
                 WHERE schema_name = 'pandemic'""") == 1
assert scalar("SELECT COUNT(*) FROM pandemic.infectious_cases") == 10_521

# --- завдання 2: нормалізація без втрат
assert scalar("SELECT COUNT(*) FROM pandemic.entities") == 245
assert scalar("SELECT COUNT(*) FROM pandemic.disease_cases") == 10_521
assert scalar("""SELECT COUNT(*) FROM pandemic.disease_cases d
                 LEFT JOIN pandemic.entities e USING (entity_id)
                 WHERE e.entity_id IS NULL""") == 0
assert scalar("""SELECT COUNT(*)
                 FROM pandemic.infectious_cases ic
                 JOIN pandemic.entities e      ON e.entity = TRIM(ic.entity)
                 JOIN pandemic.disease_cases d ON d.entity_id = e.entity_id
                                              AND d.year = ic.year::SMALLINT
                 WHERE d.number_rabies IS DISTINCT FROM ic.number_rabies::NUMERIC""") == 0

# --- завдання 3: топ-10, відсортований за середнім
top = frame("""
    SELECT e.entity,
           COUNT(d.number_rabies) AS years_observed,
           AVG(d.number_rabies)   AS avg_rabies,
           MIN(d.number_rabies)   AS min_rabies,
           MAX(d.number_rabies)   AS max_rabies,
           SUM(d.number_rabies)   AS sum_rabies
    FROM pandemic.disease_cases d
    JOIN pandemic.entities e USING (entity_id)
    GROUP BY e.entity_id, e.entity
    HAVING COUNT(d.number_rabies) > 0
    ORDER BY avg_rabies DESC
    LIMIT 10
""").astype({"avg_rabies": float, "min_rabies": float,
             "max_rabies": float, "sum_rabies": float})
assert len(top) == 10
assert top["avg_rabies"].is_monotonic_decreasing
assert top["avg_rabies"].notna().all()
assert (top["min_rabies"] <= top["avg_rabies"]).all()
assert (top["avg_rabies"] <= top["max_rabies"]).all()
# AVG рахується по не-NULL значеннях: avg * years_observed = sum
assert ((top["avg_rabies"] * top["years_observed"] - top["sum_rabies"]).abs() < 1e-6).all()

# --- завдання 4 і 5: вбудований вираз і власна функція дають однаковий результат
assert scalar("""SELECT COUNT(*) FROM pandemic.disease_cases
                 WHERE pandemic.years_since_year(year::INT)
                       IS DISTINCT FROM
                       EXTRACT(YEAR FROM AGE(CURRENT_DATE,
                                             MAKE_DATE(year::INT, 1, 1)))::INT""") == 0
assert scalar("SELECT pandemic.years_since_year(1996)") == scalar(
    "SELECT EXTRACT(YEAR FROM AGE(CURRENT_DATE, DATE '1996-01-01'))::INT")
assert scalar("SELECT pandemic.years_since_year(NULL)") is None

# --- завдання 5: друга функція
assert float(scalar("SELECT pandemic.avg_cases_per_period(1200, 12)")) == 100.00
assert float(scalar("SELECT pandemic.avg_cases_per_period(1200, 4)")) == 300.00
assert float(scalar("SELECT pandemic.avg_cases_per_period(1200, 2)")) == 600.00
assert scalar("SELECT pandemic.avg_cases_per_period(1200, 0)") is None
assert scalar("SELECT pandemic.avg_cases_per_period(NULL, 12)") is None

# --- завдання 5: відбір числових значень трьома способами
counts = frame(r"""
    SELECT
        (SELECT COUNT(*) FROM pandemic.infectious_cases
          WHERE number_rabies ~ '^-?[0-9]+(\.[0-9]+)?([eE][-+]?[0-9]+)?$')           AS by_regex,
        (SELECT COUNT(*) FROM pandemic.infectious_cases
          WHERE number_rabies IS NOT NULL
            AND pg_input_is_valid(number_rabies, 'numeric'))                         AS by_parser,
        (SELECT COUNT(*) FROM pandemic.disease_cases WHERE number_rabies IS NOT NULL) AS typed
""").iloc[0]
assert counts["by_regex"] == counts["by_parser"] == counts["typed"] == 6_780

print("Усі перевірки пройдено:")
print("  завдання 1 — схема pandemic, 10 521 рядок у staging")
print("  завдання 2 — entities 245 / disease_cases 10 521, без втрат і сиріт")
print("  завдання 3 — топ-10 за середнім Number_rabies, сортування й агрегати коректні")
print("  завдання 4 — різниця в роках вбудованими функціями")
print("  завдання 5 — обидві функції створені, узгоджені з вбудованим виразом і працюють у запитах")

Усі перевірки пройдено:
  завдання 1 — схема pandemic, 10 521 рядок у staging
  завдання 2 — entities 245 / disease_cases 10 521, без втрат і сиріт
  завдання 3 — топ-10 за середнім Number_rabies, сортування й агрегати коректні
  завдання 4 — різниця в роках вбудованими функціями
  завдання 5 — обидві функції створені, узгоджені з вбудованим виразом і працюють у запитах

---

## Підсумок

1. **Схема й імпорт.** `pandemic` створена, 10 521 рядок завантажено серверним `COPY` у
   staging-таблицю з колонками `TEXT`. Профіль даних показав розрідженість (від 0.7 % до
   80 % заповненості по колонках), відсутність нечислових значень і те, що пара
   `(Entity, Year)` — природний ключ.
2. **Нормалізація.** Залежність `Entity → Code` (часткова залежність від ключа) винесена
   в довідник `entities`; `disease_cases` тримає 9 показників з ключем `(entity_id, year)` і
   `FOREIGN KEY` на довідник. Декомпозиція без втрат — підтверджено порівнянням кожного
   показника зі staging (`mismatched_rows = 0`).
3. **Аналітика.** `AVG` / `MIN` / `MAX` / `SUM` по `Number_rabies` з сортуванням за середнім
   і `LIMIT 10`. Важливий нюанс PostgreSQL — `DESC NULLS FIRST` за замовчуванням, тому
   сутності без спостережень відфільтровані `HAVING`. Топ очікувано займають агрегати
   (`World`, групи WB і WHO); серед країн лідирують Індія та Китай.
4. **Різниця в роках.** `MAKE_DATE` + `CURRENT_DATE` + `AGE` дають колонку повних років;
   показано, чим `AGE` відрізняється від віднімання календарних років і коли ця різниця
   проявляється.
5. **Власні функції.** `years_since_year(year)` (`LANGUAGE sql`, `STABLE`) повторює логіку
   завдання 4 і збігається з ним на всіх 10 521 рядку; `avg_cases_per_period(cases, divisor)`
   (`plpgsql`, `IMMUTABLE`) дає середнє за період для дільників 12 / 4 / 2 і безпечно
   обробляє `NULL` та нульовий дільник. Обидві використані в запитах — і на типізованій
   таблиці, і на staging з фільтром числових значень.